### ISSUE TITLE
Feat: 카테고리명으로 다이어리 페이징 조회 기능 구현

### ISSUE THREAD

**Issue by ParkJh38** [Codiary-UMC-6th/Backend-Codiary#55]
## 🍒 IssueName
> 카테고리명으로 다이어리 페이징 조회 기능 구현

## 📝 Description
> 카테고리명으로 다이어리 페이징 조회 기능 구현

## 🌱 Todo
- [x] 카테고리명으로 다이어리 페이징 조회 기능 구현

**Comment by melitina915** [comment]
혹시 해당 기능이 메인페이지에서 글 조회할 때
회원이 설정한 관심 카테고리탭 누르면 해당 글들 9개씩 뜨는 기능일까요??
카테고리 관련이라고 생각했어서 초반에 제가 구현해야 된다고 인식하고 있었는데,
이미 구현하고 계시다면 재현님께 맡기고 카테고리 기능들 완성 후 다른 기능으로 넘어가려고 합니다 :)

아 그리고 Post Entity 관련하여 궁금한 것이 있는데,
Post.java에서 postCategory 변수도 있고 Category 테이블이랑 연결되는 categoriesList도 있던데
혹시 이렇게 둘 다 설정하신 이유가 있으실까요?
어떻게 설계하고 사용하셨는지 알고싶어 여쭤봅니다 :D

**Comment by ParkJh38** [comment]
@melitina915 
- 혹시 해당 기능이 메인페이지에서 글 조회할 때
회원이 설정한 관심 카테고리탭 누르면 해당 글들 9개씩 뜨는 기능일까요?? 
--> 아닙니다, 제가 구현한 부분은 다이어리 제목 검색하는 것과 같이 카테고리명을 검색하면 해당 카테고리를 가진 모든 다이어리를 조회하도록 했습니다!
--> 회원이 설정한 관심 카테고리탭 누르면 해당 글들 9개씩 뜨는 기능은 채은님이 그대로 해주시면 될것 같습니다!

- Post 엔티티 부분은 처음에 글에 카테고리 추가하는 기능을 만들때 매핑이 잘못된 부분이 남아있었습니다. 카테고리명으로 조회하는 기능 개발할때 Post 엔티티에서 불필요한 postCategory 변수는 제거하였습니다!

**Comment by melitina915** [comment]
그렇군요 덕분에 궁금한 점들이 해소되었어요 답변해주셔서 감사드립니다!
